load("@rules//yosys:yosys_synthesis.bzl", "yosys_synthesis")

yosys_synthesis(
    name = "blinky",
    srcs = ["blinky.sv"],
    top = "blinky",
    parameters = {"DIVIDER": "3"},
    vhdl_units = ["counter.counter"],
    deps = ["//vhdl/counter:counter"],
)
